<?php
/*
 *	Made by Coldfire - https://coldfiredzn.com
 *
 *  RadomeWEB Template Variables
 */

$radomeweb_local_version = "1.0";
$coldfire_url = "https://verira.com";
$support_url = "https://discord.verira.com/";

$radomeweb_settings_array = array(

    /* Setting name, then default value, then frontend var (if applicable) */

    array('logo_webp', '/uploads/logos/logo.webp', 'THEME_LOGO_WEBP'),
    array('header_bg_webp', '/custom/templates/RadomeWEB/img/bg.webp', ''),
    array('pbg_webp', '', ''),
    array('ebg_webp', '/custom/templates/RadomeWEB/img/errorbg.webp', 'THEME_E_BG_WEBP'),
    array('lbg_webp', '/custom/templates/RadomeWEB/img/loginbg.webp', 'THEME_L_BG_WEBP'),
    array('rbg_webp', '/custom/templates/RadomeWEB/img/registerbg.webp', 'THEME_R_BG_WEBP'),
    array('navbar_size', 'medium', ''),
    array('particles', 'yes', ''),
    array('ext_update', 'yes', 'THEME_EXT_UPDATE'),
    array('custom_css', '', ''),
    array('header_bg', '/custom/templates/RadomeWEB/img/bg.jpg', ''),
    array('pbg', '', ''),
    array('logo', '', 'THEME_LOGO'),
    array('ts', 'icon', 'THEME_TS'),
    array('al', 'yes', 'THEME_AL'),
    array('links', 'gwh', ''),
    array('dark', 'yes', 'THEME_DARK'),
    array('card_rounded', 'yes', 'THEME_CARD_ROUNDED'),
    array('bg_height', '270px', ''),
    array('bg_height_m', '250px', ''),
    array('navbar', 'bottom', 'THEME_NAVBAR'),
    array('ebg', '/custom/templates/RadomeWEB/img/errorbg.jpg', 'THEME_E_BG'),
    array('lbg', '/custom/templates/RadomeWEB/img/loginbg.png', 'THEME_L_BG'),
    array('rbg', '/custom/templates/RadomeWEB/img/registerbg.jpg', 'THEME_R_BG'),
    array('elr_logo', '250px', 'THEME_ELR_LOGO'),
    array('elr_margin', '150px', 'THEME_ELR_MARGIN'),
    array('wb_s1', '6011d988377d4a3489af570b2397ea61', 'THEME_WB_S1'),
    array('wb_s2', '449bfe5d39ea407eb52bfb8f093f2637', 'THEME_WB_S2'),
    array('wb_s3', 'ce5a752ace874b029464de883a8495c5', 'THEME_WB_S3'),
    array('wb_s4', 'bf232ed38a564985a05f71d2f5a6d0e1', 'THEME_WB_S4'),
    array('wb_s5', 'a62ddc8186f84298adb290bbea5d0932', 'THEME_WB_S5'),
    array('wb_s6', 'd77c98db8636414ab844195c996127fb', 'THEME_WB_S6'),
    array('wb_t', ' Sunucumuza hoşgeldin!', 'THEME_WB_T'),
    array('wb_d', 'Sunucumuza katılmak için giriş yapabilir veya hesabın yoksa kayıt olabilirsin.', 'THEME_WB_D'),
    array('wb_1n', 'Giriş Yap', 'THEME_WB_1N'),
    array('wb_1l', '/giris', 'THEME_WB_1L'),
    array('wb_2n', 'Kayıt Ol', 'THEME_WB_2N'),
    array('wb_2l', '/kayit', 'THEME_WB_2L'),
    array('font', 'Montserrat', 'THEME_FONT'),
    array('p_color', '#203C5C', ''),
    array('s_color', '#18243c', ''),   
    array('logo_size', '200px', ''),
    array('logo_size_m', '180px', ''),
    array('coverlay', 'yes', 'THEME_C_OVERLAY'),
    array('portal_bg', 'custom/templates/RadomeWEB/img/portal-bg.png', 'THEME_PORTAL_BG'),
    array('portal1_icon', '/custom/templates/RadomeWEB/img/Forums.png', 'PORTAL_1_ICON'),
    array('portal2_icon', '/custom/templates/RadomeWEB/img/Vote.png', 'PORTAL_2_ICON'),
    array('portal3_icon', '/custom/templates/RadomeWEB/img/Shop.png', 'PORTAL_3_ICON'),
    array('portal1_link', '/forum', 'PORTAL_1_LINK'),
    array('portal2_link', '/vote', 'PORTAL_2_LINK'),
    array('portal3_link', 'https://verira.com', 'PORTAL_3_LINK'),
    array('portal_logo', '250px', 'PORTAL_LOGO_SIZE'),
    array('portal_logo_m', '200px', 'PORTAL_LOGO_SIZE_M'),
    array('portal_lm', '50px', 'PORTAL_LOGO_MARGIN'),
    array('portal_lmm', '25px', 'PORTAL_LOGO_MARGIN_M'),
    array('portal_im', '300px', 'PORTAL_IMAGE_MARGIN'),
    array('portal_imm', '250px', 'PORTAL_IMAGE_MARGIN_M'),
    array('ds_box', 'yes', 'THEME_DS_BOX'),
    array('about', 'Verira.com 2021 yılında faliyete geçmiş. İstanbul / PremierDC merkezli, bünyesinde piyasada bulunan en yeni donanımları barındıran. Oyun sunucuları odaklı hosting sağlayıcısıdır.', 'THEME_ABOUT'),
    array('other_t', 'Store', 'THEME_OTHER_T'),
    array('other_d', 'Verira.com üzerinden 20TLden başlayan fiyatlarla VDS kiralayabilirsiniz', 'THEME_OTHER_D'),
    array('other_bt', 'VERIRA.COM', 'THEME_OTHER_BT'),
    array('other_bl', 'https://verira.com', 'THEME_OTHER_BL'),
    array('news_btn', 'false', 'THEME_NEWS_BTN'),
    array('news_link', '', 'THEME_NEWS_LINK'),
    array('discord_server', 'verira.com/dc', 'THEME_DISCORD_SERVER'),
    array('slider1_title', '', 'THEME_SLIDER1_TITLE'),
    array('slider1_desc', 'Admin panelinden bu kısmı değiştirebilirsiniz!', 'THEME_SLIDER1_DESCRIPTION'),
    array('slider1_image', '/custom/templates/RadomeWEB/img/slider1.png', 'THEME_SLIDER1_IMAGE'),
    array('slider1_link', 'https://verira.com', 'THEME_SLIDER1_LINK'),
    array('slider2_title', 'Resim #2', 'THEME_SLIDER2_TITLE'),
    array('slider2_desc', 'Admin panelinden bu kısmı değiştirebilirsiniz!', 'THEME_SLIDER2_DESCRIPTION'),
    array('slider2_image', '/custom/templates/RadomeWEB/img/slider2.png', 'THEME_SLIDER2_IMAGE'),
    array('slider2_link', 'https://verira.com', 'THEME_SLIDER2_LINK'),
    array('slider3_title', 'Resim #3', 'THEME_SLIDER3_TITLE'),
    array('slider3_desc', 'Admin panelinden bu kısmı değiştirebilirsiniz!', 'THEME_SLIDER3_DESCRIPTION'),
    array('slider3_image', '/custom/templates/RadomeWEB/img/slider3.png', 'THEME_SLIDER3_IMAGE'),
    array('slider3_link', 'https://verira.com', 'THEME_SLIDER3_LINK'),
    array('slider4_title', '', 'THEME_SLIDER4_TITLE'),
    array('slider4_desc', 'Admin panelinden bu kısmı değiştirebilirsiniz!', 'THEME_SLIDER4_DESCRIPTION'),
    array('slider4_image', '/custom/templates/RadomeWEB/img/slider4.png', 'THEME_SLIDER4_IMAGE'),
    array('slider4_link', 'https://verira.com', 'THEME_SLIDER4_LINK'),
    array('slider5_title', '', 'THEME_SLIDER5_TITLE'),
    array('slider5_desc', 'Admin panelinden bu kısmı değiştirebilirsiniz!l', 'THEME_SLIDER5_DESCRIPTION'),
    array('slider5_image', '/custom/templates/RadomeWEB/img/slider2.png', 'THEME_SLIDER5_IMAGE'),
    array('slider5_link', 'https://verira.com', 'THEME_SLIDER5_LINK'),
    array('slider1_link_open', 'no', 'THEME_SLIDER1_LINK_OPEN'),
    array('slider2_link_open', 'no', 'THEME_SLIDER2_LINK_OPEN'),
    array('slider3_link_open', 'no', 'THEME_SLIDER3_LINK_OPEN'),
    array('slider4_link_open', 'no', 'THEME_SLIDER4_LINK_OPEN'),
    array('slider5_link_open', 'no', 'THEME_SLIDER5_LINK_OPEN')
);